
server:
  port: 8083

spring:
  application:
    name: stock-service
  datasource:
    url: jdbc:mysql://localhost:3306/stock
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    database-platform:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    javax:
      persistence:
        validation:
          mode: none


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
