spring:
  application:
    name: stock-service
  datasource:
    url: jdbc:mysql://localhost:3306/stock
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    database-platform:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    javax:
      persistence:
        validation:
          mode: none



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}
server:
  port: 0
