spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        default-label: main
        git:
          uri: https://github.com/MedetHasanUgurlu/e-commerce-microservice-confighub
          force-pull: true
server:
  port: 8888